//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatsMarkSheetBlank
    {
        public string Name { get; set; }
        public string ADM { get; set; }
        public Nullable<int> KCPE { get; set; }
        public string ENG { get; set; }
        public string KIS { get; set; }
        public string MATHS { get; set; }
        public string CHEM { get; set; }
        public string BIO { get; set; }
        public string PHY { get; set; }
        public string GEOG { get; set; }
        public string HIST { get; set; }
        public string CRE { get; set; }
        public string AGRIC { get; set; }
        public string BST { get; set; }
        public string Total { get; set; }
        public string Points { get; set; }
        public string Year { get; set; }
        public string Term { get; set; }
        public string STREAM { get; set; }
        public string CAT { get; set; }
        public string FORM { get; set; }
        public string Grade { get; set; }
        public string EngGrade { get; set; }
        public string KisGrade { get; set; }
        public string ChemGrade { get; set; }
        public string MathGrade { get; set; }
        public string HistGrade { get; set; }
        public string PhyGrade { get; set; }
        public string GeogGrade { get; set; }
        public string BstGrade { get; set; }
        public string CreGrade { get; set; }
        public string AgricGrade { get; set; }
        public string BioGrade { get; set; }
        public string EngFinal { get; set; }
        public string KisFinal { get; set; }
        public string MathsFinal { get; set; }
        public string ChemFinal { get; set; }
        public string BioFinal { get; set; }
        public string PhyFinal { get; set; }
        public string GeogFinal { get; set; }
        public string HistFinal { get; set; }
        public string CreFinal { get; set; }
        public string AgricFinal { get; set; }
        public string BstFinal { get; set; }
        public string ClassPosition { get; set; }
        public string StreamPosition { get; set; }
        public string Gender { get; set; }
    }
}
